'use client';

import { useState } from 'react';
import { 
  AlertTriangle, 
  Clock, 
  CheckCircle, 
  FileText, 
  Lightbulb, 
  Download,
  AlertCircle,
  CheckSquare,
  Square
} from 'lucide-react';
import api from '@/lib/axios';
import { toast } from 'react-hot-toast';

interface ComplianceItem {
  id: string;
  title: string;
  description?: string;
  isCompleted?: boolean;
  priority?: string;
  dueDate?: string;
  act?: string;
  penaltyInfo?: string;
  notes?: string;
}

interface ComplianceDashboardProps {
  data?: {
    id?: string;
    reportId?: string;
    businessType?: string;
    state?: string;
    headcount?: number;
    revenueBracket?: string;
    complianceItems?: ComplianceItem[];
    content?: string;
  };
}

export default function ComplianceDashboard({ data }: ComplianceDashboardProps) {
  const [items, setItems] = useState<ComplianceItem[]>(data?.complianceItems || []);
  const [isExportingPdf, setIsExportingPdf] = useState(false);

  const reportId = data?.reportId || data?.id;
  const businessType = data?.businessType || 'Business';
  const state = data?.state || 'India';

  const completedCount = items.filter(i => i.isCompleted).length;
  const urgentCount = items.filter(i => (i.priority === 'URGENT' || i.priority === 'HIGH') && !i.isCompleted).length;
  const upcomingCount = items.filter(i => !i.isCompleted && (i.priority !== 'URGENT' && i.priority !== 'HIGH')).length;

  const toggleItem = async (itemId: string, currentStatus: boolean) => {
    if (!reportId) return;
    const newStatus = !currentStatus;

    // Optimistic update
    setItems(prev => prev.map(item => item.id === itemId ? { ...item, isCompleted: newStatus } : item));

    try {
      const response = await api.patch(`/compliance/${reportId}/items/${itemId}`, {
        isCompleted: newStatus
      });
      if (response.data && (response.data.status === 'success' || response.data.success)) {
        toast.success(newStatus ? 'Marked as completed' : 'Marked as incomplete');
      } else {
        throw new Error('Update failed');
      }
    } catch (err) {
      console.error('Failed to update item:', err);
      toast.error('Failed to update status.');
      // Rollback
      setItems(data?.complianceItems || []);
    }
  };

  const handleExportDocx = () => {
    const title = `LexAI Compliance Audit — ${businessType} (${state})`;
    const itemsHtml = items.map((item, idx) => `
      <li>
        <strong>${item.title}:</strong> ${item.isCompleted ? 'COMPLETED' : (item.priority || 'PENDING')}
        ${item.description ? `<p>${item.description}</p>` : ''}
        ${item.penaltyInfo ? `<p><em>${item.penaltyInfo}</em></p>` : ''}
      </li>
    `).join('');

    const content = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head>
        <meta charset='utf-8'/>
        <title>${title}</title>
      </head>
      <body style="font-family: Arial, sans-serif; padding: 20px; color: #111;">
        <h1 style="color: #c9a84c;">LexAI — Compliance Audit Report</h1>
        <h2>${businessType} (${state})</h2>
        <p><em>Based on applicable Indian Corporate Laws & Tax Rules. Issued by LexAI Compliance Engine.</em></p>
        <hr/>
        <h3>Executive Summary</h3>
        <ul>
          <li><strong>Urgent Action Items:</strong> ${urgentCount}</li>
          <li><strong>Upcoming Obligations:</strong> ${upcomingCount}</li>
          <li><strong>Compliant Items:</strong> ${completedCount} / ${items.length}</li>
        </ul>
        <h3>Compliance Obligations & Checklist</h3>
        <ol>
          ${itemsHtml || '<li>Full audit checklist available in online workspace.</li>'}
        </ol>
        <br/>
        <p><em>⚖️ Generated by LexAI Sovereign Intelligence. Confidential Corporate Document.</em></p>
      </body>
      </html>
    `;
    const blob = new Blob(['\ufeff' + content], { type: 'application/msword' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Compliance_Report_${businessType}_${state}.docx`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleExportPdf = async () => {
    if (!reportId || isExportingPdf) return;
    setIsExportingPdf(true);

    try {
      const res = await api.post(`/compliance/${reportId}/export/pdf`);
      if (res.data && (res.data.status === 'success' || res.data.success || res.status === 202)) {
        toast.loading(res.data.message || 'PDF generation started. Download will start automatically...', { id: `pdf-${reportId}` });

        let pollCount = 0;
        const interval = setInterval(async () => {
          pollCount++;
          if (pollCount > 30) {
            clearInterval(interval);
            setIsExportingPdf(false);
            toast.error('PDF generation timed out.', { id: `pdf-${reportId}` });
            return;
          }

          try {
            const reportRes = await api.get(`/compliance/${reportId}`);
            if (reportRes.data && (reportRes.data.status === 'success' || reportRes.data.success) && reportRes.data.data?.pdfUrl) {
              clearInterval(interval);
              setIsExportingPdf(false);
              toast.success('PDF ready! Starting download...', { id: `pdf-${reportId}` });

              const link = document.createElement('a');
              link.href = reportRes.data.data.pdfUrl;
              link.setAttribute('download', `Compliance_Report_${reportId}.pdf`);
              link.setAttribute('target', '_blank');
              document.body.appendChild(link);
              link.click();
              document.body.removeChild(link);
            }
          } catch (pollErr) {
            console.error('Polling error:', pollErr);
          }
        }, 2000);
      }
    } catch (err) {
      console.error('PDF trigger error:', err);
      setIsExportingPdf(false);
      toast.error('Failed to trigger PDF export.');
    }
  };

  return (
    <div className="w-full space-y-6">
      {/* Header Section */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="space-y-1">
          <span className="font-mono text-[11px] font-semibold text-gold tracking-[0.2em] uppercase">
            Compliance Audit Report
          </span>
          <h2 className="font-serif text-[24px] md:text-[28px] font-semibold text-text-primary leading-tight">
            {businessType} — {state}
          </h2>
          <p className="text-text-secondary text-[13px] mt-1">
            Real-time regulatory analysis based on Indian Statutory Laws & Acts.
          </p>
        </div>
        
        <div className="flex items-center gap-2 shrink-0">
          <button
            onClick={handleExportDocx}
            className="flex items-center gap-2 px-3.5 py-2 bg-gold/10 border border-gold-border hover:bg-gold hover:text-bg-primary text-gold rounded-lg text-[12px] font-medium transition-all cursor-pointer shadow-sm"
          >
            <Download size={14} />
            Export DOCX
          </button>
          {reportId && (
            <button
              onClick={handleExportPdf}
              disabled={isExportingPdf}
              className="flex items-center gap-2 px-3.5 py-2 bg-bg-tertiary border border-border-default hover:border-gold text-text-primary rounded-lg text-[12px] font-medium transition-all cursor-pointer disabled:opacity-50"
            >
              <Download size={14} className={isExportingPdf ? 'animate-bounce' : ''} />
              Export PDF
            </button>
          )}
        </div>
      </div>

      {/* Summary Row */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {/* Urgent Items */}
        <div className="bg-bg-secondary border border-error/20 rounded-xl p-5 relative overflow-hidden group hover:border-error/40 transition-colors duration-200">
          <h3 className="text-error text-[40px] font-serif leading-none font-semibold">{urgentCount}</h3>
          <p className="text-text-secondary text-[12px] font-medium mt-1 uppercase tracking-wider">
            Urgent Obligations
          </p>
          <div className="mt-4 flex items-center gap-1.5 text-[11px] text-error bg-error/10 w-fit px-2.5 py-0.5 rounded-md font-medium">
            <AlertTriangle size={12} /> High Priority
          </div>
        </div>

        {/* Upcoming Items */}
        <div className="bg-bg-secondary border border-warning/20 rounded-xl p-5 relative overflow-hidden group hover:border-warning/40 transition-colors duration-200">
          <h3 className="text-warning text-[40px] font-serif leading-none font-semibold">{upcomingCount}</h3>
          <p className="text-text-secondary text-[12px] font-medium mt-1 uppercase tracking-wider">
            Upcoming Filings
          </p>
          <div className="mt-4 flex items-center gap-1.5 text-[11px] text-warning bg-warning/10 w-fit px-2.5 py-0.5 rounded-md font-medium">
            <Clock size={12} /> Scheduled
          </div>
        </div>

        {/* Completed Items */}
        <div className="bg-bg-secondary border border-success/20 rounded-xl p-5 relative overflow-hidden group hover:border-success/40 transition-colors duration-200">
          <h3 className="text-success text-[40px] font-serif leading-none font-semibold">{completedCount}</h3>
          <p className="text-text-secondary text-[12px] font-medium mt-1 uppercase tracking-wider">
            Completed Obligations
          </p>
          <div className="mt-4 flex items-center gap-1.5 text-[11px] text-success bg-success/10 w-fit px-2.5 py-0.5 rounded-md font-medium">
            <CheckCircle size={12} /> Compliant
          </div>
        </div>
      </div>

      {/* Audit Checklist Section */}
      {items.length > 0 && (
        <div className="space-y-3">
          <h4 className="font-serif text-[18px] font-semibold text-text-primary">
            Statutory Checklist & Obligations
          </h4>

          <div className="bg-bg-secondary border border-border-default rounded-xl divide-y divide-border-default overflow-hidden">
            {items.map((item) => (
              <div 
                key={item.id}
                className="p-4 md:p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4 hover:bg-bg-tertiary/40 transition-colors duration-150"
              >
                <div className="flex items-start gap-4">
                  <button
                    onClick={() => toggleItem(item.id, !!item.isCompleted)}
                    className="mt-0.5 text-text-muted hover:text-gold transition-colors cursor-pointer shrink-0"
                  >
                    {item.isCompleted ? (
                      <CheckSquare className="text-success" size={20} />
                    ) : (
                      <Square size={20} />
                    )}
                  </button>

                  <div className="space-y-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <h5 className={`text-[14px] font-medium ${item.isCompleted ? 'line-through text-text-muted' : 'text-text-primary'}`}>
                        {item.title}
                      </h5>
                      <span className={`px-2 py-0.5 text-[9px] rounded font-bold tracking-wider uppercase border ${
                        item.isCompleted 
                          ? 'bg-success/10 border-success/20 text-success'
                          : item.priority === 'URGENT' || item.priority === 'HIGH'
                          ? 'bg-error/20 border-error/30 text-error'
                          : 'bg-warning/10 border-warning/20 text-warning'
                      }`}>
                        {item.isCompleted ? 'Completed' : (item.priority || 'Pending')}
                      </span>
                    </div>

                    {item.description && (
                      <p className="text-text-secondary text-[12px]">
                        {item.description}
                      </p>
                    )}

                    {item.penaltyInfo && !item.isCompleted && (
                      <p className="text-error text-[11px] flex items-center gap-1">
                        <AlertCircle size={11} /> {item.penaltyInfo}
                      </p>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Regulatory Insight */}
      <div className="bg-gold-subtle border border-gold-border rounded-xl p-5 relative overflow-hidden group">
        <div className="flex gap-4 relative z-10">
          <div className="shrink-0 p-1.5 rounded-lg bg-gold/10 text-gold border border-gold/20 h-fit">
            <Lightbulb size={20} strokeWidth={1.5} />
          </div>
          <div className="space-y-1">
            <h4 className="text-gold font-serif text-[15px] font-semibold">
              LexAI Statutory Intelligence
            </h4>
            <p className="text-text-secondary text-[13px] leading-relaxed">
              Compliance requirements are dynamically compiled from MCA, Income Tax, GST, and Labour Regulation databases according to business structure and state regulations.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
